on:
  workflow_dispatch

jobs:
  manual-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install MikTex
        run: |
          DISTRIB_CODENAME=$(grep -Po "(?<=^DISTRIB_CODENAME=).*" /etc/lsb-release)
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb http://miktex.org/download/ubuntu ${DISTRIB_CODENAME} universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt-get update
          sudo apt-get install texlive-full texlive-lang-all
          
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build pdf
        run: |
         pdftex --output-directory=/ /master.tex
